---
title: "Use Chinese General Social Survey Data"
author: "Yi YIN"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

##  Search question to obtian the index in the dataset
```{r}
library(cgssr)
data(cgss2003)
data(codebook2003_en)
ques_search_en("trust",codebook2003_en)
```

## Get to know the answer labels of the variable
```{r}
codebook2003_en$label_en[codebook2003_en$index=='truststr']
```


## Exploratory Analysis
```{r}
table(cgss2003$truststr)
```


```{r, fig.show='hold'}
library(ggplot2)
ggplot(data = cgss2003, aes(truststr)) + 
                    geom_bar() + 
                    xlab("")+
                    ylab("")+
                    ggtitle("Degree of trust in strangers")+
                    theme_classic(base_family = 'Palatino')+
                    theme(plot.title = element_text(hjust = 0.5))
```

